

<!--The footer holds the link to my webiste ELAHMAWY DEV , All rights of design is setntenced to ELASHMAWY DEV-->
<footer>
   <div>
       developed by <a href="https://elashmawydev.com" style="color: #1dd1a1;cursor: pointer;">ELASHMAWY DEV</a>
   </div> 
</footer>
<div class="alarms" id="alarms">
    </div>

<script src="<?=PUBLIC_URL;?>assets/js/ajax.js"></script>
<script src="<?=PUBLIC_URL;?>assets/js/main.js"></script>
<script src="<?=PUBLIC_URL;?>assets/js/datepicker.js"></script>
<script src="<?=PUBLIC_URL;?>assets/js/maps.js"></script>
<script async defer
src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDgEJDrHfcUOfgkT7QeZmU1Uak32KxYYcM">
</script>

</body>
</html>