<div class="main-container">
    <div class="page-position">
        <h2>لوحة التحكم</h2>
        <p>/</p>
        <h6>الأخبار</h6>
    </div>
    <?php echo !empty($this->showNews) ? $this->showNews : null; ?>
    <div class="container news">
        <div class="add-new">
            <button class="btn-add-new-news" onclick="popupBox('.add-news-box')">أضف خبر جديد</button>
        </div>
        <div class="table-container">
            <div class="table">
                <table>
                    <thead>
                        <tr>
                            <th>#</th>
                            <th colspan="5">الخبر</th>
                            <th>التاريخ</th>
                            <th>الإجراء</th>
                        </tr>
                    </thead>
                    <tbody>

                        <?php foreach ($this->news as $news) : ?>
                            <tr>
                                <td><?= $news->id; ?></td>
                                <td colspan="5"><?= $news->news; ?></td>
                                <td><?= $news->create_date; ?></td>
                                <td class="action">
                                    <img onclick="popupBox('.delete-news-box'); get_news_delete(this);" src="<?php echo PUBLIC_URL; ?>assets/img/trash.svg" alt="حذف الخبر" title="حذف الخبر" data-news-id="<?php echo $news->id; ?>" class="delete_user_btn">
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
            <div class="pagination" data-update-function="searchForNews">
            </div>
        </div>
    </div>
</div>


<!--Add New news Box BEGIN-->
<div class="float-box-container">

    <div class="add-news-box">
        <!--Closing Tag Start-->
        <div class="closing" onclick="closeBox(this)">
            <span></span>
            <span></span>
        </div>
        <!--Closing Tag END-->
        <form method="POST">
            <h3>إضافة خبر جديد</h3>
            <div class="input-items">
                <div class="input-item"><textarea name="news" placeholder="الخبر"></textarea></div>
                <div class="input-item"><button class="add-btn" type="submit" name="add_news">اضافة</button></div>
            </div>
        </form>

    </div>
</div>
<!--Add New news Box END-->






<!--Delete news Box BEGIN-->
<div class="float-box-container">

    <div class="delete-news-box">
        <!--Closing Tag Start-->
        <div class="closing" onclick="closeBox(this)">
            <span></span>
            <span></span>
        </div>
        <!--Closing Tag END-->
        <form method="POST" name="delete_news_form">
            <input type="hidden" name="id">
            <h3>حذف الخبر رقم #<span class="news_id"></span></h3>
            <div class="input-items">
                <div class="input-item"><button class="delete-btn" type="submit" name="delete_news">حذف</button></div>
                <div class="input-item"><button class="abort-btn" type="" onclick="abort('.delete-news-box')">الغاء</button></div>
            </div>
        </form>

    </div>
</div>
<!--Delete news Box END-->



<script>
    const searchForNews = () => {
        updateNewsTable({
            page: current_page
        });
    }
</script>