
<div class="main-container">
    <div class="page-position">
        <h2>لوحة التحكم</h2>
        <p>/</p>
        <h6>المستخدمين</h6>
    </div>
    <?=!empty($this->showNews) ? $this->showNews : null;?>
    <div class="container users">
        <div class="search-container">
            <h3>البحث المتقدم</h3>
            <div class="search-box">
                <input type="text" placeholder="اسم المستخدم" id="username-search">
                <input type="text" placeholder="البريد الالكتروني" id="email-search">
                <input type="text" placeholder="الاسم" id="name-search">
                <input type="text" placeholder="رقم الهاتف" id="phone-search">
                <input type="number" placeholder="#" id="id-search">
                <div class="select-item">
                    <select id="lvl-search" onclick="rotateSelect(this)">
                        <option value="">المستوي</option>
                        <?php if($this->role('مدير')):?>
                        <option value="مدير">مدير</option>
                        <?php endif;?>
                        <option value="مشرف">مشرف</option>
                        <option value="فني">فني</option>
                    </select>
                    <span></span>
                </div>
                
            </div>
        </div>
        <div class="add-new">
            <button class="btn-add-new-user" id="add_new_user_btn" onclick="popupBox('.add-user-box')">أضف جديد</button>
        </div>
        <div class="table-container">
            <div class="table">
                <table>
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>اسم المستخدم</th>
                            <th>البريد الالكتروني</th>
                            <th>الاسم</th>
                            <th>رقم الهاتف</th>
                            <th>المستوي</th>
                            <th>أخر مرة تسجيل دخول</th>
                            <th>الإجراء</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach($this->data as $user):?>
                        <tr>
                            <td><?=$user->id;?></td>
                            <td><?=$user->username;?></td>
                            <td><?=$user->email;?></td>
                            <td><?=$user->name;?></td>
                            <td><?=$user->phone;?></td>
                            <td><?=$user->lvl;?></td>                            
                            <td><?=$user->login_date?></td>
                            <!--Signed user => Don't show buttons-->
                            <td class="action">
                                <?php if($_SESSION['id'] != $user->id):?>
                                <button onclick="get_user_edit(this)" class="btn-edit edit_user_btn" data-user-id="<?=$user->id;?>">تعديل</button>
                                <img onclick="popupBox('.delete-user-box'); get_user_delete(this);" src="<?=PUBLIC_URL;?>assets/img/trash.svg" alt="حذف المستخدم" title="حذف المستخدم" data-user-id="<?=$user->id;?>" class="delete_user_btn">

                                <?php endif;?>
                            </td>
                        </tr>
                        <?php endforeach;?>
                    </tbody>
                </table>
            </div>
            <div class="pagination">

            </div>
        </div>
    </div>
</div>



<!--Add New user Box BEGIN-->
<div class="float-box-container">

    <div class="add-user-box">
        <!--Closing Tag Start-->
        <div class="closing" onclick="closeBox(this)">
            <span></span>
            <span></span>
        </div>
        <!--Closing Tag END-->
        <form method="POST">
            <h3>إضافة مستخدم جديد</h3>
            <div class="input-items">
                <div class="select-item">
                    <select name="lvl" onclick="rotateSelect(this);">
                        <option value="">المستوي</option>
                        <option value="مدير">مدير</option>
                        <option value="مشرف">مشرف</option>
                        <option value="فني">فني</option>
                    </select>
                    <span></span>
                </div>
                <div class="input-item"><label>اسم المستخدم</label><input type="text" name="username" placeholder="اسم المستخدم"></div>
                <div class="input-item"><label>البريد الالكتروني</label><input type="text" name="email" placeholder="البريد الالكتروني"></div>
                <div class="input-item"><label>الاسم</label><input type="text" name="name" placeholder="الاسم"></div>
                <div class="input-item"><label>رقم الهاتف</label><input type="text" name="phone" placeholder="رقم الهاتف"></div>
                <div class="input-item"><label>كلمة المرور</label><input type="password" name="pass1" placeholder="كلمة المرور"></div>
                <div class="input-item"><label>تأكيد كلمة المرور</label><input type="password" name="pass2" placeholder="تأكيد كلمة المرور"></div>
                <div class="input-item"><button class="save-btn" type="submit" name="add_new_user">اضافة</button></div>
            </div>
        </form>
        
    </div>
</div>
<!--Add New user Box END-->


<!--Edit user Box BEGIN-->
<div class="float-box-container">

    <div class="edit-user-box">
        <!--Closing Tag Start-->
        <div class="closing" onclick="closeBox(this)">
            <span></span>
            <span></span>
        </div>
        <!--Closing Tag END-->
        <form method="POST" onsubmit="edit_user(this)">
            <input type="hidden" name="id">
            <h3>تعديل بيانات المستخدم رقم <span class="user_id"></span></h3>
            <div class="input-items">
                <div class="select-item">
                    <select name="lvl" onclick="rotateSelect(this);">
                        <option value="">المستوي</option>
                        <option value="مدير">مدير</option>
                        <option value="مشرف">مشرف</option>
                        <option value="فني">فني</option>
                    </select>
                    <span></span>
                </div>
                <div class="input-item"><label>اسم المستخدم</label><input type="text" name="username" placeholder="اسم المستخدم"></div>
                <div class="input-item"><label>البريد الالكتروني</label><input type="text" name="email" placeholder="البريد الالكتروني"></div>
                <div class="input-item"><label>الاسم</label><input type="text" name="name" placeholder="الاسم"></div>
                <div class="input-item"><label>رقم الهاتف</label><input type="text" name="phone" placeholder="رقم الهاتف"></div>
                <div class="input-item"><button class="save-btn" type="submit">تعديل</button></div>
            </div>
        </form>

        <span></span>
        <h3>تغيير كلمة المرور</h3>
        <form method="POST" name="change_user_password_form">
            <input type="hidden" name="id">
            <div class="input-items">
                <div class="input-item"><label>كلمة المرور الجديدة</label><input type="password" name="pass1" placeholder="كلمة المرور الجديدة"></div>
                <div class="input-item"><label>تأكيد كلمة المرور</label><input type="password" name="pass2" placeholder="تأكيد كلمة المرور"></div>
                <div class="input-item"><button class="save-btn" type="submit" name="change_user_password">تحديث كلمة المرور</button></div>
            </div>
        </form>
    </div>
</div>
<!--Edit user Box END-->


<!--Delete user Box BEGIN-->
<div class="float-box-container">

    <div class="delete-user-box">
        <!--Closing Tag Start-->
        <div class="closing" onclick="closeBox(this)">
            <span></span>
            <span></span>
        </div>
        <!--Closing Tag END-->
        <form method="POST" onsubmit="delete_user(this)">
            <input type="hidden" name="id">
            <h3>حذف المستخدم رقم <span class="user_id"></span></h3>
            <div class="input-items">
                <div class="input-item"><button class="delete-btn" type="submit">حذف</button></div>
                <div class="input-item"><button class="abort-btn" type="" onclick="abort('.delete-user-box')">الغاء</button></div>
            </div>
        </form>
        
    </div>
</div>
<!--Delete user Box END-->


<script>

    //search with username
    let username_search = document.querySelector('#username-search');
    username_search.oninput = e => searchInput(username_search, 2);

    //search with email
    let email_search = document.querySelector('#email-search');
    email_search.oninput = e => searchInput(email_search, 3);

    //search with name
    let name_search = document.querySelector('#name-search');
    name_search.oninput = e => searchInput(name_search, 4);

    //search with phone
    let phone_search = document.querySelector('#phone-search');
    phone_search.oninput = e => searchInput(phone_search, 5);

    //search with id
    let id_search = document.querySelector('#id-search');
    id_search.oninput = e => searchInput(id_search, 1);

    //search with lvl
    let lvl_search = document.querySelector('#lvl-search');
    lvl_search.onchange = e => searchInput(lvl_search, 6);


    //form validation
    let change_user_password_form = document.forms['change_user_password_form'];
    change_user_password_form.onsubmit = e => {
        if(change_user_password_form['pass1'].value == '') {
            e.preventDefault();
            messages(['يجب كتابة كلمة المرور']);  
        } else if (change_user_password_form['pass2'].value == '') {
            e.preventDefault();
            messages(['يجب تأكيد كلمة المرور']);
        } else if (change_user_password_form['pass2'].value != change_user_password_form['pass1'].value) {
            e.preventDefault();
            messages(['يجب أن تكون كلمتي المرور متطابقتان']);
        } 

        
    }
</script>
